"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { useCart } from "./CartProvider";
import { OrderMenuCard } from "./OrderMenuCard";
import { finishOrderRequest, orderRequest, requestKey } from "@/lib/order-client";
import { formatPrice } from "@/lib/utils";
import type { CatalogResponse, OrderMenuProps } from "@/types";

export function OrderMenu({ initialMenu, tableCode }: OrderMenuProps): React.JSX.Element {
 const cart=useCart(), router=useRouter(); const [catalog,setCatalog]=useState<CatalogResponse>({menu:initialMenu,tables:[],configured:false,onlinePayment:false}); const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
 useEffect(()=>{void fetch("/api/catalog",{cache:"no-store"}).then(r=>r.ok?r.json():null).then(data=>{if(data?.configured)setCatalog(data)}).catch(()=>undefined)},[]);
 const total=useMemo(()=>cart.items.reduce((sum,line)=>sum+(catalog.menu.find(x=>x.id===line.menuItemId)?.price??0)*line.quantity,0),[cart.items,catalog.menu]);
 async function checkout(form:FormData):Promise<void>{setBusy(true);setError("");try{const fulfillment=String(form.get("fulfillment"));const payload={customerName:String(form.get("name")),phone:String(form.get("phone")),fulfillment,tableCode:fulfillment==="dine_in"?String(form.get("table")||tableCode):undefined,paymentMethod:"cod" as const,items:cart.items};const idempotencyKey=await requestKey("checkout",payload);const result=await orderRequest<{order:{id:string}}>("/api/orders",{method:"POST",body:JSON.stringify({...payload,idempotencyKey})},true);finishOrderRequest("checkout",result.order.id);cart.clear();router.push(`/order/${result.order.id}`)}catch(cause){setError(cause instanceof Error?cause.message:"Pesanan belum terkirim.")}finally{setBusy(false)}}
 return <section className="mx-auto max-w-5xl px-5 py-10 md:py-16"><p className="text-xs font-semibold uppercase tracking-[.2em] text-latte">Pesan di meja</p><h1 className="mt-3 font-serif text-4xl">Pilih yang ingin dinikmati.</h1><p className="mt-3 text-sm text-offwhite-muted">{tableCode?`Meja ${tableCode} terdeteksi.`:"Pilih makan di tempat atau bawa pulang saat checkout."} Bayar di kasir tersedia. Pembayaran online segera hadir.</p><div className="mt-8 grid gap-x-10 md:grid-cols-2">{catalog.menu.filter(i=>i.isAvailable!==false).map(item=><OrderMenuCard key={item.id} item={item} quantity={cart.items.find(x=>x.menuItemId===item.id)?.quantity??0} onAdd={()=>cart.add(item.id)}/>)}</div><div className="sticky bottom-4 mt-8 flex items-center justify-between rounded-2xl border border-latte/30 bg-espresso p-4 shadow-floating"><span className="text-sm text-offwhite">{cart.count} item · {formatPrice(total)}</span><button disabled={!cart.count} onClick={()=>setOpen(true)} className="min-h-11 rounded-xl bg-terracotta px-5 text-sm font-semibold disabled:opacity-50">Checkout</button></div>{open&&<div className="fixed inset-0 z-[100] grid place-items-center bg-black/70 p-5"><form action={checkout} className="w-full max-w-md rounded-2xl bg-charcoal p-6"><h2 className="font-serif text-2xl">Detail pesanan</h2><p className="mt-2 text-xs text-offwhite-muted">Bayar di kasir · {formatPrice(total)}</p><label className="mt-5 block text-sm">Nama<input required name="name" minLength={2} className="mt-2 w-full rounded-lg border border-charcoal-border bg-charcoal-darkest p-3"/></label><label className="mt-4 block text-sm">Nomor WhatsApp<input required name="phone" inputMode="tel" className="mt-2 w-full rounded-lg border border-charcoal-border bg-charcoal-darkest p-3"/></label><label className="mt-4 block text-sm">Untuk<select name="fulfillment" defaultValue={tableCode?"dine_in":"takeaway"} className="mt-2 w-full rounded-lg border border-charcoal-border bg-charcoal-darkest p-3"><option value="dine_in">Makan di tempat</option><option value="takeaway">Bawa pulang</option></select></label><label className="mt-4 block text-sm">ID meja (untuk makan di tempat)<input name="table" defaultValue={tableCode} className="mt-2 w-full rounded-lg border border-charcoal-border bg-charcoal-darkest p-3"/></label>{error&&<p role="alert" className="mt-4 text-sm text-terracotta-light">{error}</p>}<div className="mt-6 flex gap-3"><button type="button" onClick={()=>setOpen(false)} className="min-h-11 flex-1 rounded-lg border border-charcoal-border">Batal</button><button disabled={busy} className="min-h-11 flex-1 rounded-lg bg-terracotta font-semibold">{busy?"Mengirim…":"Kirim pesanan"}</button></div></form></div>}<Link className="mt-8 inline-block text-sm text-latte underline underline-offset-4" href="/">← Kembali ke CafeSite</Link></section>;
}
