import { revalidatePath } from "next/cache";
import { apiError, authorizeStaff, bodyJson, dbError, json } from "@/lib/server/api";
import { HttpError, numberValue, objectValue, textValue, uuidValue } from "@/lib/server/validation";
import type { ModuleId } from "@/types";
const contentResources=["cafe","gallery","testimonials","faq","location"] as const;
type Resource=ModuleId|"floors"|"modules"|"categories";
function resource(url:URL):Resource{const value=url.searchParams.get("resource");if(!value||!["menu","tables","floors","cafe","gallery","testimonials","faq","location","reports","modules","categories"].includes(value))throw new HttpError(400,"Modul tidak valid.");return value as Resource}
function permission(res:Resource):ModuleId|"admin"{return res==="modules"?"admin":res==="floors"?"tables":res==="categories"?"menu":res}
function tableId(value:unknown):string{const id=textValue(value,"ID meja",40);if(!/^[A-Za-z0-9_-]{1,40}$/.test(id))throw new HttpError(400,"ID meja hanya boleh berisi huruf, angka, garis bawah, atau tanda hubung.");return id}
export async function GET(request:Request):Promise<Response>{try{const res=resource(new URL(request.url));const {db}=await authorizeStaff(request,permission(res));if(res==="categories"){const {data,error}=await db.from("content").select("data").eq("key","categories").maybeSingle();if(!error&&data?.data)return json({data:data.data});const cafe=await db.from("content").select("data").eq("key","cafe").maybeSingle();if(cafe.data?.data&&Array.isArray((cafe.data.data as Record<string,unknown>).categories))return json({data:(cafe.data.data as Record<string,unknown>).categories});return json({data:null})}if(contentResources.includes(res as typeof contentResources[number])){const {data,error}=await db.from("content").select("data").eq("key",res).maybeSingle();dbError(error);return json({data:data?.data??null})}if(res==="menu"){const {data,error}=await db.from("menu_items").select("id,data,is_available,sort_order").order("sort_order");dbError(error);return json({data:data??[]})}if(res==="tables"){const [floors,tables]=await Promise.all([db.from("floors").select("*").order("sort_order"),db.from("cafe_tables").select("*")]);dbError(floors.error);dbError(tables.error);return json({floors:floors.data??[],tables:tables.data??[]})}if(res==="modules"){const {data,error}=await db.from("staff_modules").select("*");dbError(error);return json({data:data??[]})}return json({data:[]})}catch(error){return apiError(error)}}
export async function PUT(request:Request):Promise<Response>{try{const res=resource(new URL(request.url));const {db}=await authorizeStaff(request,permission(res));const body=await bodyJson(request);if(res==="categories"){const catResult=await db.from("content").upsert({key:"categories",data:body.data});if(catResult.error){const cafeRes=await db.from("content").select("data").eq("key","cafe").maybeSingle();const currentCafe=(cafeRes.data?.data&&typeof cafeRes.data.data==="object"?cafeRes.data.data:{})as Record<string,unknown>;const updateRes=await db.from("content").upsert({key:"cafe",data:{...currentCafe,categories:body.data}});dbError(updateRes.error);}revalidatePath("/","layout");return json({ok:true})}if(contentResources.includes(res as typeof contentResources[number])){const {error}=await db.from("content").upsert({key:res,data:body.data});dbError(error);revalidatePath("/","layout");return json({ok:true})}if(res==="menu"){if(Array.isArray(body.reorder)){await Promise.all(body.reorder.map(async(row:unknown)=>{const rec=objectValue(row);const id=textValue(rec.id,"ID menu",80);const sortOrder=numberValue(rec.sort_order,"Urutan",0,100000);const {error}=await db.from("menu_items").update({sort_order:sortOrder}).eq("id",id);dbError(error);}));revalidatePath("/","layout");return json({ok:true})}const item=objectValue(body.item);const id=textValue(item.id,"ID menu",80);const price=numberValue(item.price,"Harga",0,10000000);const data={...item,id,price};const {error}=await db.from("menu_items").upsert({id,data,is_available:item.isAvailable!==false,sort_order:typeof body.sortOrder==="number"?body.sortOrder:0});dbError(error);revalidatePath("/","layout");return json({ok:true})}if(res==="floors"){const floor=objectValue(body.floor);const record:{id?:string;name:string;sort_order:number}={name:textValue(floor.name,"Nama lantai",80),sort_order:numberValue(floor.sortOrder,"Urutan lantai",0,10000)};if(floor.id!==undefined)record.id=uuidValue(floor.id);const {error}=await db.from("floors").upsert(record);dbError(error);return json({ok:true})}if(res==="tables"){const table=objectValue(body.table);const id=tableId(table.id);const floor=uuidValue(table.floorId);if(!["available","occupied","dirty"].includes(String(table.status)))throw new HttpError(400,"Status meja tidak valid.");const {error}=await db.rpc("save_cafe_table",{table_code:id,floor_uuid:floor,table_label:textValue(table.label,"Nama meja",80),pos_x:10,pos_y:10,new_status:table.status});dbError(error);return json({ok:true})}if(res==="modules"){const id=textValue(body.id,"Modul",30);const {error}=await db.from("staff_modules").update({enabled:body.enabled===true}).eq("id",id);dbError(error);return json({ok:true})}throw new HttpError(400,"Aksi tidak tersedia.")}catch(error){return apiError(error)}}
export async function DELETE(request:Request):Promise<Response>{try{const res=resource(new URL(request.url));if(!["menu","tables","floors"].includes(res))throw new HttpError(400,"Penghapusan tidak tersedia.");const {db}=await authorizeStaff(request,permission(res));const body=await bodyJson(request);if(res==="menu"){const id=textValue(body.id,"ID menu",80);const {error}=await db.from("menu_items").delete().eq("id",id);dbError(error);revalidatePath("/","layout");return json({ok:true})}if(res==="tables"){const {error}=await db.rpc("delete_cafe_table",{table_code:tableId(body.id)});dbError(error);return json({ok:true})}const {error}=await db.from("floors").delete().eq("id",uuidValue(body.id));dbError(error);return json({ok:true})}catch(error){return apiError(error)}}
