import { revalidatePath } from "next/cache";
import { apiError, authorizeStaff, bodyJson, dbError, json } from "@/lib/server/api";
import { HttpError, numberValue, objectValue, textValue, uuidValue } from "@/lib/server/validation";
import type { ModuleId } from "@/types";
const contentResources=["cafe","gallery","testimonials","faq","location"] as const;
type Resource=ModuleId|"modules";
function resource(url:URL):Resource{const value=url.searchParams.get("resource");if(!value||!["menu","tables","cafe","gallery","testimonials","faq","location","reports","modules"].includes(value))throw new HttpError(400,"Modul tidak valid.");return value as Resource}
export async function GET(request:Request):Promise<Response>{try{const res=resource(new URL(request.url));const {db}=await authorizeStaff(request,res==="modules"?"admin":res);if(contentResources.includes(res as typeof contentResources[number])){const {data,error}=await db.from("content").select("data").eq("key",res).maybeSingle();dbError(error);return json({data:data?.data??null})}if(res==="menu"){const {data,error}=await db.from("menu_items").select("id,data,is_available,sort_order").order("sort_order");dbError(error);return json({data:data??[]})}if(res==="tables"){const [floors,tables]=await Promise.all([db.from("floors").select("*").order("sort_order"),db.from("cafe_tables").select("*")]);dbError(floors.error);dbError(tables.error);return json({floors:floors.data??[],tables:tables.data??[]})}if(res==="modules"){const {data,error}=await db.from("staff_modules").select("*");dbError(error);return json({data:data??[]})}return json({data:[]})}catch(error){return apiError(error)}}
export async function PUT(request:Request):Promise<Response>{try{const res=resource(new URL(request.url));const {db}=await authorizeStaff(request,res==="modules"?"admin":res);const body=await bodyJson(request);if(contentResources.includes(res as typeof contentResources[number])){const {error}=await db.from("content").upsert({key:res,data:body.data});dbError(error);revalidatePath("/","layout");return json({ok:true})}if(res==="menu"){const item=objectValue(body.item);const id=textValue(item.id,"ID menu",80);const price=numberValue(item.price,"Harga",0,10000000);const data={...item,id,price};const {error}=await db.from("menu_items").upsert({id,data,is_available:item.isAvailable!==false,sort_order:typeof body.sortOrder==="number"?body.sortOrder:0});dbError(error);revalidatePath("/","layout");return json({ok:true})}if(res==="tables"){const table=objectValue(body.table);const id=textValue(table.id,"ID meja",40);const floor=uuidValue(table.floorId);const {error}=await db.rpc("save_cafe_table",{table_code:id,floor_uuid:floor,table_label:textValue(table.label,"Nama meja",80),pos_x:typeof table.x==="number"?table.x:10,pos_y:typeof table.y==="number"?table.y:10,new_status:table.status??"available"});dbError(error);return json({ok:true})}if(res==="modules"){const id=textValue(body.id,"Modul",30);const {error}=await db.from("staff_modules").update({enabled:body.enabled===true}).eq("id",id);dbError(error);return json({ok:true})}throw new HttpError(400,"Aksi tidak tersedia.")}catch(error){return apiError(error)}}
export async function DELETE(request:Request):Promise<Response>{try{const res=resource(new URL(request.url));if(res!=="menu")throw new HttpError(400,"Penghapusan tidak tersedia.");const {db}=await authorizeStaff(request,"menu");const body=await bodyJson(request);const id=textValue(body.id,"ID menu",80);const {error}=await db.from("menu_items").delete().eq("id",id);dbError(error);revalidatePath("/","layout");return json({ok:true})}catch(error){return apiError(error)}}
